version: '3.9'

services:
  webapi:
    build:
      context: ./BankSystem
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: banksystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres